#***************************************************************************************
# Copyright (c) 2025 Institute of Computing Technology, Chinese Academy of Sciences
# Copyright (c) 2024-2025 Beijing Institute of Open Source Chip (BOSC)
#
# DiffTest is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
#
# See the Mulan PSL v2 for more details.
#***************************************************************************************

GSIM_BIN ?= gsim
CXX = clang++  # only support clang++14 or above

GSIM_EMU_TARGET    = $(abspath $(BUILD_DIR)/gsim)
GSIM_EMU_BUILD_DIR = $(abspath $(BUILD_DIR)/gsim-compile)

##############################################
### Running GSIM to generate cpp model
##############################################

GSIM_GEN_CSRC_DIR = $(GSIM_EMU_BUILD_DIR)/model
GSIM_FLAGS = --supernode-max-size=35 --cpp-max-size-KB=8192

$(GSIM_GEN_CSRC_DIR)/$(SIM_TOP)0.cpp: $(RTL_DIR)/$(SIM_TOP).fir
	@mkdir -p $(@D)
	$(GSIM_BIN) $(GSIM_FLAGS) --dir $(@D) $< | tee $(GSIM_EMU_BUILD_DIR)/gsim-gen-cpp.log

gsim-gen-cpp: $(GSIM_GEN_CSRC_DIR)/$(SIM_TOP)0.cpp

##############################################
### Building EMU from cpp model generated by GSIM
##############################################

GSIM_CONFIG_DIR = $(abspath ./config)
VERILITOR_CSRC_DIR = $(abspath ./src/test/csrc/verilator)
GSIM_OTHER_CSRC_DIR = $(abspath ./src/test/csrc/gsim)
GSIM_CXXFILES = $(SIM_CXXFILES) $(shell find $(VERILITOR_CSRC_DIR) $(GSIM_OTHER_CSRC_DIR) -name "*.cpp")

GSIM_CXXFLAGS = $(subst \\\",\", $(SIM_CXXFLAGS)) -DNUM_CORES=$(NUM_CORES) -DGSIM \
						-I$(VERILITOR_CSRC_DIR) -I$(GEN_VSRC_DIR) \
						-I$(GSIM_GEN_CSRC_DIR)/ \
						-O3 \
						-fbracket-depth=2048 -Wno-parentheses-equality
LDFLAGS   =  $(SIM_LDFLAGS) -ldl

# $(1): object file
# $(2): source file
# $(3): compile flags
# $(4): object file list
# $(5): extra dependency
define CXX_TEMPLATE =
$(1): $(2) $(THIS_MAKEFILE) $(5)
	@mkdir -p $$(@D) && echo + CXX $$<
	@$(CXX) $$< $(3) -c -o $$@
$(4) += $(1)
endef

# $(1): object file
# $(2): source file
# $(3): ld flags
define LD_TEMPLATE =
$(1): $(2)
	@mkdir -p $$(@D) && echo + LD $$@
	@$(CXX) $$^ $(3) -o $$@
endef

$(foreach x, $(GSIM_CXXFILES), $(eval \
	$(call CXX_TEMPLATE, $(GSIM_EMU_BUILD_DIR)/other/$(basename $(notdir $(x))).o, $(x), $(GSIM_CXXFLAGS), GSIM_EMU_OBJS,)))

$(foreach x, $(shell find $(GSIM_GEN_CSRC_DIR) -name "*.cpp" 2> /dev/null), $(eval \
	$(call CXX_TEMPLATE, $(GSIM_EMU_BUILD_DIR)/model/$(basename $(notdir $(x))).o, $(x), $(GSIM_CXXFLAGS), GSIM_EMU_OBJS,)))

$(eval $(call LD_TEMPLATE, $(GSIM_EMU_TARGET), $(GSIM_EMU_OBJS), $(LDFLAGS)))

gsim-gen-emu: $(GSIM_EMU_TARGET)

gsim:
	$(MAKE) gsim-gen-cpp
	$(MAKE) gsim-gen-emu
