set defines [list \
  XIANGSHAN_FPGA \
  RANDOMIZE_GARBAGE_ASSIGN \
  RANDOMIZE_REG_INIT \
  RANDOMIZE_MEM_INIT \
  RANDOMIZE_DELAY=1 \
  DDR4_16G_X8 \
  DQ64 \
  DDR4_2400 \
  DQ=64 \
  MICRON_DDR \
  DDR4_16Gbx8 \
  DDR4 \
  SRAM_SYN \
]
